alter session set container = XEPDB1;

-- Special characters such as the ampersand will result in prompt without this directive.
SET DEFINE OFF;

-- Categories
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (1, 'Aperture');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (2, 'BCM');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (3, 'BELS');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (4, 'BLM');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (5, 'Beam Dump');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (6, 'Box PS');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (7, 'CAMAC');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (8, 'Cryo');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (9, 'Demand Power');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (10, 'Gun');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (11, 'Harp');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (12, 'Helicity');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (13, 'IOC');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (14, 'Ion Chamber');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (15, 'LCW');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (16, 'Laser');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (17, 'MO');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (18, 'Misc');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (19, 'ODH');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (20, 'RF');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (21, 'RF Separators');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (22, 'RadCon');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (23, 'Trim');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (24, 'Trim Rack');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (25, 'Vacuum Pump');
INSERT INTO JAWS_OWNER.CATEGORY (CATEGORY_ID, NAME) VALUES (26, 'Warm RF');

DROP SEQUENCE JAWS_OWNER.CATEGORY_ID;
CREATE SEQUENCE JAWS_OWNER.CATEGORY_ID
    INCREMENT BY 1
    START WITH 27
    NOCYCLE
    NOCACHE
    ORDER;

-- Locations
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (1, null, 'SITE');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (2, 1, 'CEBAF');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (3, 1, 'CHL');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (4, 1, 'LERF');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (5, 1, 'UITF');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (6, 2, 'Injector');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (7, 2, 'North Linac');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (8, 2, 'South Linac');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (9, 2, 'East Arc');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (10, 2, 'West Arc');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (11, 2, 'BSY');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (12, 2, 'HallA');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (13, 2, 'HallB');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (14, 2, 'HallC');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (15, 2, 'HallD');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (16, 6, '1D');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (17, 6, '2D');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (18, 6, '3D');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (19, 6, '4D');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (20, 6, '5D');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (21, 9, 'ARC1');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (22, 9, 'ARC3');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (23, 9, 'ARC5');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (24, 9, 'ARC7');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (25, 9, 'ARC9');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (26, 10, 'ARC2');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (27, 10, 'ARC4');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (28, 10, 'ARC6');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (29, 10, 'ARC8');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (30, 10, 'ARCA');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (31, 11, 'BSY Dump');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (32, 11, 'BSY2');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (33, 11, 'BSY4');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (34, 11, 'BSY6');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (35, 11, 'BSY8');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (36, 11, 'BSYA');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (37, 7, 'Linac1');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (38, 7, 'Linac3');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (39, 7, 'Linac5');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (40, 7, 'Linac7');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (41, 7, 'Linac9');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (42, 8, 'Linac2');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (43, 8, 'Linac4');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (44, 8, 'Linac6');
INSERT INTO JAWS_OWNER.LOCATION (LOCATION_ID, PARENT_ID, NAME) VALUES (45, 8, 'Linac8');

DROP SEQUENCE JAWS_OWNER.LOCATION_ID;
CREATE SEQUENCE JAWS_OWNER.LOCATION_ID
    INCREMENT BY 1
    START WITH 46
    NOCYCLE
    NOCACHE
    ORDER;